export const ROUTE_TITLES: Record<string, string> = {
  '/dashboard': 'Tổng quan',
  '/transactions': 'Giao dịch',
  '/tanks': 'Bồn bể',
  '/pumps': 'Theo dõi trụ bơm',
  '/shifts': 'Ca bán hàng',
  '/fuel-inventory': 'Kho nhiên liệu',
  '/fuel-prices': 'Giá nhiên liệu',
  '/customers': 'Khách hàng',
  '/fuel-supply': 'Cấp nhiên liệu',
  '/debts': 'Công nợ',
  '/invoices': 'Hóa đơn',
  '/reports': 'Báo cáo',
  '/users': 'Người dùng',
  '/settings': 'Cài đặt',
};
